version: '3'
services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
    - postgresql
    links:
      - postgresql:postgres
    networks: 
      - pg-network
    environment:
      PGHOST: 'postgres'
      PGUSER: solinfo
      PGDATABASE: solinfodemo
      PGPASSWORD: solinfo123

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: solinfo
      POSTGRES_DB: solinfodemo
      POSTGRES_PASSWORD: solinfo123
    networks: 
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "4001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'daniel.solinfo@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: solinfo123
    links:
      - postgresql:postgres
    networks: 
      - pg-network
    

networks: 
  pg-network:
    driver: bridge