CREATE TABLE documentos (
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          varchar(80),    
    autor           varchar(80),
    importante      int DEFAULT 0,
    creado_el       date
  );